### ISSUE TITLE
Bring `life-sync` feature to print executing command

### ISSUE THREAD

**Issue by ChShersh** [kowainik/summoner#110]
Change instance to this one:

```haskell
instance (a ~ Text, b ~ ()) => IsString ([a] -> IO b) where
    fromString cmd args = do
        let cmdStr = showCommandForUser cmd (map toString args)
        putStrLn $ "⚙  " ++ cmdStr
        callCommand cmdStr
```

**Comment by willbasky** [comment]
What is this feature about? Where is piece of code from?

**Comment by ChShersh** [comment]
@willbasky This issue is about changing this instance in `summoner`:

https://github.com/kowainik/summoner/blob/6b1c87e23c1c8f55f706c615869af8fa73cb6cd7/src/Summoner/Process.hs#L23-L26

to prettier instance from `life-sync`:

https://github.com/kowainik/life-sync/blob/e537e372e34539ad1325e2685687d61f68869eb4/src/Life/Shell.hs#L45-L50
