### ISSUE TITLE
Doesn't work when only `cabal` project is created

### ISSUE THREAD

**Issue by ChShersh** [kowainik/summoner#117]
`summoner` doesn't `cd` into directory when only `cabal` project is created. This resulted in whole my home directory uploaded to Github as a single repository. And I didn't like it...

I think the reason for this is because system call to `"cd"` doesn't change current working directory:

https://github.com/kowainik/summoner/blob/96b10338c4296c2363913f15236ea49a602b14f0/src/Summoner/Project.hs#L123

Previously, there was special case for `cd` in that redirected call to `setCurrentDirectory` function:

* https://hackage.haskell.org/package/directory-1.3.3.1/docs/System-Directory.html#v:setCurrentDirectory

But it doesn't do this anymore. And turns out that this is important.

**Comment by vrom911** [comment]
😱 Oh my

Thanks for pointing this out.

We need some tests!

**Comment by ChShersh** [comment]
@vrom911 Well, I assume that after every such change at least some manual testing is performed. When I tested this locally last time, I didn't push, I just watched at commands. So I didn't notice it. I still have no idea how to make automatic tests for this.
