### ISSUE TITLE
Print directories bold when tree is printed

### ISSUE THREAD

**Issue by ChShersh** [kowainik/summoner#124]
Use `setSGRCode` from `ansi-terminal` library:

* http://hackage.haskell.org/package/ansi-terminal-0.8.0.4/docs/System-Console-ANSI.html#v:setSGRCode

**Comment by willbasky** [comment]
@ChShersh Am I right that bold should be applied inside `Tree.hs`?

**Comment by ChShersh** [comment]
@willbasky You're totally right :+1:
