### ISSUE TITLE
Split `Summoner.Template` into smaller pieces

### ISSUE THREAD

**Issue by ChShersh** [kowainik/summoner#125]
This is a first step towards refactoring to `update` command. We're going to use `named` library for this:

* https://hackage.haskell.org/package/named-0.2.0.0/docs/Named.html

**Comment by ChShersh** [comment]
After looking at current template files I can propose the following separation (not sure whether it makes sense or not). @vrom911, please, look and leave any comments 🙂 

* `Template.Haskell`
    + `.cabal` file
    + library
    + prelude
    + executable
    + test-suite
    + bench
* `Template.Stack`
    + `stack.yaml`
* `Template.Doc`
    + `LICENSE`
    + `.gitignore`
    + `README.md`
    + `CHANGELOG.md`
    + `CONTRIBUTING.md`
    + `.stylish-haskell.yaml`
* `Template.CI`
    + `.travis.yml`
    + `appveyor.yml`

**Comment by vrom911** [comment]
I'm not sure if `Template.Github` is better than `Template.CI`, but if that was me I would suggest it and also put `.gitignore` in there. Otherwise looks nice!

**Comment by ChShersh** [comment]
@vrom911 Another possibility is to name it as `Template.Configs` and put there `.stylish-haskell.yaml` as well (but I don't like `Configs` name). Maybe something like `External` for _external tools_ or `Integrations` for GitHub + Travis + AppVeyor + stylish-haskell?

I also was thinking about having `Template.Cabal` for `.cabal` only file.

What do you think?

**Comment by vrom911** [comment]
We can make `Cabal` module as well ( I have a feeling that in the future we will need to generate more cabal specific files, like `cabal.project`).

If you can come up with the intuitive name I don't mind having GitHub and stylish in one module, but for now I find `Github` module more pretty.

**Comment by ChShersh** [comment]
@vrom911 I've updated the module hierarchy. Please, check, whether it makes more sense now 🙂
