### ISSUE TITLE
Improve tree output

### ISSUE THREAD

**Issue by ChShersh** [kowainik/summoner#126]
Currently `summoner` prints this output when project is created:

```
  test-package/
  │── .gitignore
  │── .travis.yml
  │── CHANGELOG.md
  │── LICENSE
  │── README.md
  │── app/
  │   └── Main.hs
  │── benchmark
  │   └── Main.hs
  │── src/
  │   │── Prelude.hs
  │   └── TestPackage.hs
  │── stack-8.2.2.yaml
  │── stack.yaml
  │── test/
  │   └── Spec.hs
  └── test-package.cabal
```

However, it can be slightly prettier (compare with `tree` command-line utility):

```
test-package/
├── .gitignore
├── .travis.yml
├── CHANGELOG.md
├── LICENSE
├── README.md
├── app
│   └── Main.hs
├── benchmark
│   └── Main.hs
├── src
│   ├── Prelude.hs
│   └── TestPackage.hs
├── stack-8.2.2.yaml
├── stack.yaml
├── test
│   └── Spec.hs
└── test-package.cabal
```

**Comment by willbasky** [comment]
Improve via applying `tree` command?

**Comment by ChShersh** [comment]
@willbasky Without `tree` command. We don't want `summoner` users to install `tree` command-line utility. So current pretty-printing function for `Tree` should be patched instead.

**Comment by chris-bacon** [comment]
Hello @ChShersh, just taking a look at this one. 

Just to clarify, the only real difference I can see between the output there is that `tree` doesn't include dotfiles. Are you looking for just dotfiles to be removed from the `Summoner.Tree` output?

Cheers

**Comment by vrom911** [comment]
Hey @chris-bacon 👋  
I guess this description can be misleading, sorry for that. This issue is not about removing the output of the dotfiles, and it is actually useful to see. The idea is to show it in a more beautiful way using better Unicode symbols for representing the tree (so the lines are uninterrupted).
I will update the description accordingly as well.

**Comment by sam46** [comment]
Hey I think I can help out with this. Total noob here btw

**Comment by sam46** [comment]
Done!

**Comment by chris-bacon** [comment]
Oh I see @vrom911 - thanks for the update. Beat me to it @sam46 ;)
