### ISSUE TITLE
Add versions to `base` dependency

### ISSUE THREAD

**Issue by ChShersh** [kowainik/summoner#142]
It's possible since we know GHC versions for project.

**Comment by ChShersh** [comment]
@Leschonander I appreciate your desire to help! The issue is about adding version constraints for `base` package in `build-depends` in generated by `summoner` projects. This is relevant to lines like this one:

https://github.com/kowainik/summoner/blob/765fea39ba58fd5a79e62319f6ee8485bd4d2efb/src/Summoner/Template.hs#L195

Currently `summoner` generates project with the following `.cabal` piece:

```cabal
build-depends: base
```

While in reality it should add version constraints according to the chosen GHC versions. Something like this:

```cabal
build-depends: base >= 4.10 && < 5
```

We already have a function for detecting `base` versions according to GHC version, only need to use it in templates for generating project:

https://github.com/kowainik/summoner/blob/765fea39ba58fd5a79e62319f6ee8485bd4d2efb/src/Summoner/GhcVer.hs#L40-L46

**Comment by vrom911** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [foo](https://trello.com/c/dt7YyTVZ/7-foo)
