### ISSUE TITLE
Auto completion command and options

### ISSUE THREAD

**Issue by willbasky** [kowainik/summoner#147]
`optparse-applicative` has enabled support for options and commands. (not only Bash)
To switch it on Ubuntu:
```summon --bash-completion-script `which summon` | sudo tee /etc/bash_completion.d/summon```
on macOs:
```summon --bash-completion-script `which summon` | sudo tee /usr/local/etc/bash_completion.d/summon```
At a minimum, this can be added to `Readme`, at a maximum, via instalation.

To complete arguments is necessary to code a little.

**Comment by willbasky** [comment]
Ops, it is already :)

**Comment by ShrykeWindgrace** [comment]
Is there a version without `sudo`?

**Comment by willbasky** [comment]
I am not sure. `/etc/bash_completion.d/` is directory with root rights.

**Comment by ChShersh** [comment]
@willbasky @ShrykeWindgrace Current `README.md` file already contains information about enabling autocompletion for `summoner` without `sudo`:

```haskell
source <(summon --bash-completion-script `which summon`)
```

Though, it doesn't work on macOS. But I guess macOS has it's own way to handle autocompletion. Personally I had to install some package just to enable autocompletion for `git` on macOS.

**Comment by willbasky** [comment]
Doesn`t 
```
summon --bash-completion-script `which summon` | sudo tee /usr/local/etc/bash_completion.d/summon
```
work on MacOs?

**Comment by ChShersh** [comment]
@willbasky Will check tomorrow. But my answer was about the fact, that non-`sudo` version doesn't work on macOS :disappointed:

**Comment by willbasky** [comment]
On my Linux is also.

**Comment by willbasky** [comment]
Can`t we give to installer `root` rights to add some file to that directory automatically?

**Comment by ChShersh** [comment]
I've checked this on macOS and it seems to work :+1:
