### ISSUE TITLE
GitHub releases + package managers

### ISSUE THREAD

**Issue by chshersh** [kowainik/summoner#159]
Meta-issue for tracking progress on learning how to generate releases of `summoner` to make it more convenient to install. Splits into two sections:

1. From sources
2. Binaries in GitHub releases (to be able to download and use it quickly).
3. Package managers (to install directly from terminal).

Specifically:

* From source/Hackage:
    - [x] Cabal from sources
    - [x] Cabal from Hackage
    - [x] Stack from sources
    - [x] `stack install`
* GitHub releases:
    - [x] Linux x64
    - [x] macOS
    - [x] Windows x64
* Package managers:
    - [ ] Ubuntu: `apt` (probably via some PPA)
    - [x] macOS: `brew` formula ([relevant link](https://github.com/blender/homebrew-tap/blob/master/rome.rb)

The following tool looks useful for helping with GitHub releases:

* https://github.com/tfausak/github-release

**Comment by ChShersh** [comment]
@ChrisPenner thanks for the suggestion!
