### ISSUE TITLE
Github remote URL

### ISSUE THREAD

**Issue by pascalpoizat** [kowainik/summoner#167]
Hello

it seems that URLs for GitHub repos have the form `git@github.com:user/repo.git`. Would it be possible to have an option to use `https://github.com/user/repo.git` instead (I don't know why but I have issues with my ssh config on my laptop and only the second way works)?

Note: currently I use `git remote set-url origin https://github.com/user/repo.git` to update things so this is a very low priority issue :-)

**Comment by qoelet** [comment]
Hi @pascalpoizat,

not sure if this helps with your question. AFAIK, you can work with both URLS - one defaults to SSH (git@github.com:user/repo.git) and the other via HTTPS. You can also switch between the two.

They have a short article that expands on that here: https://help.github.com/articles/which-remote-url-should-i-use/

**Comment by kahlil29** [comment]
@pascalpoizat Could you please elaborate a bit more? I didn't fully understand what you need here.

**Comment by pascalpoizat** [comment]
The remote that is created by the `hub` command in function `doGithubCommands` (module `Summoner.Project`) uses SSH rather than HTTPS.
It is indeed `hub` that does this using its `create` command. So it is a `hub` related issue.
My issue corresponds to https://github.com/github/hub/issues/1614.
The solution is to run
```
git config --global hub.protocol https
```
or 
```
export HUB_PROTOCOL="ssh"
```
for a single use / session.
Hence I believe the issue can be closed (no need to add an option in summon to set HUB_PROTOCOL to either https or ssh, since the user can do it directly on a global or session-based level.

**Comment by ChShersh** [comment]
@pascalpoizat I agree with @vrom911 here. I think we should have _How to_ section in our `README.md` where we can describe all possible workarounds. For now I see two things that we can put there:

1. HTTPS for `hub`
2. `stack exec` trick to use `curl` on Windows (discussed in #137) issue.

**Comment by pascalpoizat** [comment]
wrt the last comment by @ChShersh , possibly also: 

3. manually changing `cabal` version (discussed in issue https://github.com/kowainik/summoner/issues/168)
