### ISSUE TITLE
Undo last step

### ISSUE THREAD

**Issue by willbasky** [kowainik/summoner#177]
Sometimes I misclick and wanna come back to correct the answer. But I can`t and have to come up to the end, delete project and start `summon` again or find and rewrite some parameters in configuration.

If `summon` has  `undo` command...

**Comment by ChShersh** [comment]
@willbasky Having this command would be really nice :+1: But it's not that easy to implement properly (especially if we want to support multiple `undo`s or even `redo`)

**Comment by willbasky** [comment]
I suppose a one step back without redo is good for the first time.

**Comment by vrom911** [comment]
@willbasky How do you think the design for this feature should look like?
I just can't imagine how this can be implemented 😞

**Comment by ChShersh** [comment]
I think that this issue can be closed. It's not clear how to implement this for CLI. But nowadays we have TUI mode, where you don't need undo.
