### ISSUE TITLE
Beautiful IO of the tool

### ISSUE THREAD

**Issue by vrom911** [kowainik/summoner#18]
- [x]  Use bold for default choices
- [x]  Different colours
- [x]  Input on separate line
- [x]  Add more info messages
- [x] More improvements

I will be happy to see any ideas how to make it look better.

**Comment by vrom911** [comment]
That's how the `--help` of the `hs-init` looks like:
![screenshot from 2017-10-10 20-08-06](https://user-images.githubusercontent.com/8126674/31405401-9fdbf39c-ae07-11e7-8e88-be46e2b1b576.png)
And the work of the tool itself:
![screenshot from 2017-10-10 22-08-31](https://user-images.githubusercontent.com/8126674/31405402-9ff5b296-ae07-11e7-9c09-ec9ec916db21.png)

This issue will remain open until anybody propose better interface :sparkles:

**Comment by ChShersh** [comment]
@vrom911 Now we even have magician in comments! Maybe we close this issue? 🙂 🔮

**Comment by vrom911** [comment]
You're right, thanks @ChShersh !
