### ISSUE TITLE
Rename some of the fields in the `Settings` data type

### ISSUE THREAD

**Issue by ChShersh** [kowainik/summoner#180]
This data type:

https://github.com/kowainik/summoner/blob/0a533d01bf1800a4fbe1323f40efdb66a8bbae0b/src/Summoner/Settings.hs#L16-L42

Historically some names are not perfect. Let's do the following:

1. `settingsGithub` to `settingsGitHub`
2. `settingsAppVey` to `settingsAppVeyor`
3. `settingsBase` to `settingsBaseType`

Should be ok for now :+1:

**Comment by cdeepanshu** [comment]
I would like to solve this issue.....
