### ISSUE TITLE
Add --no-upload option

### ISSUE THREAD

**Issue by vrom911** [kowainik/summoner#184]
When I'm testing the `summon` tool I usually want to create all files even GitHub-related (like Travis, Appveyor). But I don't really want to upload that to GitHub sometimes. So I propose to add `--no-upload` option. With this option `summoner` will do all the stuff it's doing usually but without the `hub` steps.

**Comment by ChShersh** [comment]
@vrom911 That's a good improvement! Especially useful when I want to test how `.travis.yml` looks like but I can't create Travis without enabling GitHub flag...

**Comment by AlexBoliachiy** [comment]
Gonna stab this one
