### ISSUE TITLE
Add golden tests for `summoner`

### ISSUE THREAD

**Issue by ChShersh** [kowainik/summoner#185]
I propose the following idea for golden tests:

1. Create projects with all options specified.
2. Copy content of this project somewhere in `test/golden/`
3. Implement automatic tests that will generate project with same settings and will compare content of every file.

**Comment by vrom911** [comment]
I propose to create two projects to cover more checks:

| Feature    | Project 1 | Project 2 |
| --------- | -------- | --------- |
| Cabal       | True      | True       |
| Stack       | True      | False       |
| License    | MIT        |  None     |
| GitHub     | True       | False         |
| Travis       | True      | False       |
| AppVeyor | True      | False       |
| Lib           | True      | False       |
| Exe          | True      | True       |
| Test          | True      | False       |
| Bench        | True      | False       |
| Prelude      | `relude`   | False       |
| GHC      | `8.0.2`, `8.2.2`, `8.4.3`   | Default       |
| Stylish      | True      | False       |
| Contribution      | True      | False      |
| Warnings      | 2 warn.      | Default       |
| Extention      | 3 ext.      | False       |

How is this plan?
