### ISSUE TITLE
Feature Request: Prompt questions not clear

### ISSUE THREAD

**Issue by kkweon** [kowainik/summoner#195]
Hi, I was not happy with stack templates and then I'm happy to find this !

But, I think some of things could be improved.
I think these questions could have been worded better.

```
Add GitHub integration? [y]/n 
  -> ...
Add Travis CI integration? [y]/n
  -> ...
Add AppVeyor CI integration? [y]/n
  -> ...
Add private repository? [y]/n
  -> ...
```

Plus, I can't find documentation what it's doing.

For example, what does it mean by "add GitHub integration"? 🤔 
What does it mean "add private repository"? 🤔 

Frankly, I was shocked when it created a private repository and pushed the first commit 😆 

So, I hope these prompts to be re-written or better documentations or better UX

For example, it could show

```
# Both should be grouped together
Create a GitHub repo and commit/push the project? [y]/n 
Create as a private GitHub repo? (Needs a private repo plan)? [y]/n


Add Travis CI Integration [y]/n
Add AppVeyor CI Integration [y]/n
```

**Comment by vrom911** [comment]
Hello @kkweon ,

Thank for your feedback! These are indeed good points and we should add these improvements to the very next release. I like your suggestions, this will make the process much clearer 👍

**Comment by kkweon** [comment]
The simplest fix I can think of is to make 

```haskell
chooseYesNo :: Text -- ^ target
            -> IO a -- ^ action for 'Y' answer
            -> IO a -- ^ action for 'N' answer
            -> IO a
```

in https://github.com/kkweon/summoner/blob/master/src/Summoner/Question.hs#L68

to

```haskell
chooseYesNo :: Text -- ^ help text
            -> Text -- ^ target
            -> IO a -- ^ action for 'Y' answer
            -> IO a -- ^ action for 'N' answer
            -> IO a
```

```diff
-    printQuestion ("Add " <> target <> "?") ["y", "n"]
+    printQuestion (helpText <> "?") ["y", "n"]
```

So, I can write a descriptive `helpText` AND still have a target to show

```
"GitHub Integration" was added to your project 
```

which is the current behavior.

But, one downside is that "help text" and "target" are closely related.

If you agree with that, I'd make a PR.

**Comment by vrom911** [comment]
@kkweon, yes, I agree, this is a fair trade off! To improve the usability we should need to add a bit of the overlapping information. Feel free to make a PR! I really appreciate your effort on this 👍

**Comment by ChShersh** [comment]
I want to add one thing, while we are on this. For stuff like `library`, `executable`, `test-suite` and `benchmark` it's better to ask _Add library stanza?_ (use `stanza` word instead of `target`) to keep closer to `cabal` semantics.
