### ISSUE TITLE
Support for unFree license(s)

### ISSUE THREAD

**Issue by o1lo01ol1o** [kowainik/summoner#199]
Or this could just be a `None` option.  There's no reason to require that someone generate and then delete an unacceptable license file and the badge from ReadMe.md.

Here's how `nix` handles it: https://github.com/NixOS/nixpkgs/blob/master/lib/licenses.nix

**Comment by vrom911** [comment]
We are supporting the licenses that are used both at GitHub and in Cabal.
Also, I can't find any good information about the license you're mentioning. Could you at least give the links on the license itself and describe a point of it (the link you provided is related to some internal stuff, not really useful as we are not using the same logic as they do)?
I also don't see it in the list of the supported by Cabal licenses: https://www.haskell.org/cabal/release/latest/doc/API/Cabal/Distribution-License.html#t:License

**Comment by o1lo01ol1o** [comment]
`AllRightsReserved`. Is how I would interpret the `unFree` license that nix uses.  I'm not a lawyer, but I believe that in absence of an explicit license (in the US anyway) rights are held by the author of the code.  In anycase, that appears to be how github "supports" exclusive rights: https://choosealicense.com/no-permission/

So the overlap between github and cabal for exclusive rights would be `AllRightsReserved`

**Comment by vrom911** [comment]
Thanks @o1lo01ol1o! I agree that we can add `None` license option which will not add any `LICENSE` file and shown in `.cabal` file as `AllRightsReserved` in that case. This also gives us the opportunity to support the offline mode for free (just use this `None` license), which was in our plans anyway, and this helps us to implement it easily!
