### ISSUE TITLE
Fix unicode symbols in TUI (for linux)

### ISSUE THREAD

**Issue by willbasky** [kowainik/summoner#237]
Now it is squares on Linux (kubuntu konsole):
![image](https://user-images.githubusercontent.com/28530747/48966439-4fd12c80-eff3-11e8-9013-e6af003071e1.png)
Must be unicode something (like on MacOS):
![image](https://user-images.githubusercontent.com/28530747/48966490-557b4200-eff4-11e8-88fd-74e3a8c19f68.png)

**Comment by ChShersh** [comment]
@willbasky I've used brackets from this list:

* https://stackoverflow.com/questions/13535172/list-of-all-unicodes-open-close-brackets

Looks like some of them are not supported in all terminals...

**Comment by ChShersh** [comment]
@willbasky Could you paste in the comment to this section what brackets your terminal can recognize? This will help us a lot! Then we can select more common unicode character. But this is really strange that not all unicode is supported in modern terminal emulators... I'm okay without support for emojis, but in my vision at least all unicode character set should be supported.

**Comment by willbasky** [comment]
![default](https://user-images.githubusercontent.com/28530747/49001320-33153000-f17e-11e8-8f11-d07e2ddea66a.png)
Belissimo!
