### ISSUE TITLE
Put common parts of the project inside `common` stanza

### ISSUE THREAD

**Issue by chshersh** [kowainik/summoner#246]
We have several things inside our project that can be put inside `common` stanza in `.cabal` file. This will decrease the size of generated `.cabal` file significantly by removing duplication and will help people to learn new `cabal` features. Unfortunately, this is available only for `cabal-2.4`. But looks like `stack` already supports this cabal version, so there shouldn't be any major problems (though, this should be verified).

Inspired by the following `cabal` issue:

* https://github.com/haskell/cabal/issues/5705

What we can put inside `common` stanza:

1. `default-language: Haskell2010`
2. `build-depends:` — `base` or `base-noprelude` with version
3. Alternative prelude library if used
4. Default warnings
5. Default extensions

**Comment by m-renaud** [comment]
Also `ghc-options`!

**Comment by m-renaud** [comment]
@ChShersh Ah yes, I was thinking stuff like `-fhide-source-paths` as you mention. For some reason I thought the configuration option was `extensions` and not `warnings`.

**Comment by ChShersh** [comment]
@m-renaud We don't have `ghc-options` field at the moment and I agree that `warnings` is not the best name. I've created the following issue though (regarding renaming `warnings` to `ghc-options`):

* https://github.com/kowainik/summoner/issues/269
