### ISSUE TITLE
Comments to different parts of the scaffolded project

### ISSUE THREAD

**Issue by vrom911** [kowainik/summoner#247]
It's not a good practice to use the library which exposes `Prelude` nodule as the dependency. It will spoil the workspace, and it would be hard to make it work with your project. Uploading such a library to Hackage/Stackage is not a good idea as well.
The way to handle it is to add `Prelude` to `other-modules`, but in this case, you're not able to share `Prelude` with your `test`/`executable`/`benchmarks` stanza. 

It's not us to decide or to figure out the purpose of the generated project, so my proposal is to add a comment in the generated `cabal` file near the `Prelude` module which will notify users of the downsides of having the `Prelude` module in the `exposed-modules` if they are going to share it as a library. 

Though, it shouldn't be a very often case.

**Comment by ChShersh** [comment]
@vrom911 This is extremely nice proposal! I like having a comment for `Prelude` module. This shouldn't be that hard. And maybe later we can figure out better solution how to share `Prelude` with stanzas but not expose `Prelude` via `exposed-modules`. Maybe some combination of internal libraries and common stanzas can help here. But, AFAIK, `stack` doesn't support internal libraries completely, so we might wait on this solution...

**Comment by ChShersh** [comment]
As discussed with @vrom911, probably not only `Prelude` module should be commented. Let's think of all places that can benefit from having comments, and add all of them in one go.

**Comment by chshersh** [comment]
On the one hand, it's good to leave comments all over the place to help beginners. On the other hand, these comments are redundant for more experienced maintainers, and they look like noise in the code. Introducing a flag to control the generation of comments seems like a non-maintainable and hacky solution. We can always write documentation in `README.md`, write more blog posts and answer issues, so I propose to close this issue.

**Comment by vrom911** [comment]
This is true! I am closing this issue in favour of more documentation/posts/etc. :+1:
