### ISSUE TITLE
cabal 2.2 changes names of BSD licenses

### ISSUE THREAD

**Issue by chessai** [kowainik/summoner#251]
With cabal 2.2 and up (ie `cabal-version: 2.2` in the cabal file), BSD3 and BSD2 are BSD-3-Clause and BSD-2-Clause, respectively. This doesn't seem to be reflected in the Licenses module, where BSD3 maps to "BSD3", likewise for BSD2.

**Comment by vrom911** [comment]
@chessai thanks for reaching out!
We are using `cabal 2.0` for the generated project, so there is no conflict in license names.
Though, we have plans to move to `2.4` soon and use the features from that version (see #246), so we will keep in mind the changes with the License naming.

**Comment by chessai** [comment]
Okay. Looks like the same can be said for other licenses. According to https://github.com/cabal/blob/master/Distribution/License.hs, the licenses are now:

GPL
GPL-2
GPL-3
AGPL
AGPL-3
LGPL
LGPL-2.1
LGPL-3
BSD-2-Clause
BSD-3-Clause
BSD-4-Clause
MIT
ISC
MPL-2.0
Apache
Apache-2.0
PublicDomain
AllRightsReserved
OtherLicense

**Comment by vrom911** [comment]
I think the link is broken, here is the working one: https://github.com/haskell/cabal/blob/master/Cabal/Distribution/License.hs#L69-L130

And thanks again. But for the coming release, we would stay with `cabal 2.0`.
Also, we are supporting the intersection of the Licenses supported at GitHub and Cabal.

**Comment by chessai** [comment]
Another thing to note is that `cabal-version` must be the top non-commented line in the cabal file, because cabal needs to know how to parse the file. and there's a weird thing with implicit greater-than, where `cabal-version: 2.2` means what older cabals would need `cabal-version: >= 2.2`.

Yeah, no problem, this isn't necessary or urgent of course. I was just reading the source and noticed this, thought I would open an issue

**Comment by vrom911** [comment]
> cabal-version must be the top non-commented line in the cabal file, because cabal needs to know how to parse the file.

Yeah, we are using this rule for all our projects and in Summoner as well. You can see that this is exactly what is in the code:

https://github.com/kowainik/summoner/blob/cf3abb978a4bfa9f74755465135bdbf272c08947/src/Summoner/Template/Cabal.hs#L33-L36

**Comment by chessai** [comment]
Cool. Thanks for the awesome project
