### ISSUE TITLE
Make `Enter` work inside `Description` field in TUI

### ISSUE THREAD

**Issue by chshersh** [kowainik/summoner#253]
Currently `Description` input field contains two lines, but <kbd>Enter</kbd> doesn't work there because we create projects on <kbd>Enter</kbd>. It's also not that clear how to handle this situation...

**Comment by NickSeagull** [comment]
Shift+Enter perhaps?

**Comment by yigitozkavci** [comment]
Hi, I intend to give this a try using `Shift+Enter` approach :)

**Comment by yigitozkavci** [comment]
Hmm, modifiers other than "Alt" are not being sent to event handler. This should be the issue you were observing.

For now I'll create a PR with `Alt-Enter` combination. It's not the most intuitive key combination but it's still better than not having a new line command, I guess.

**Comment by chshersh** [comment]
@yigitozkavci Having <kbd>Alt</kbd>+<kbd>Enter</kbd> as a solution seems fine, if there's no way to support <kbd>Shift</kbd>. Maybe the issue with <kbd>Shift</kbd> can be investigated first? Maybe we can open a bug request to `brick`? Or maybe we can try to update to the latest `brick` version and see whether we still have this issue? (but updating should be done carefully to make sure that everything rest still works correctly).

**Comment by yigitozkavci** [comment]
@chshersh That makes sense. I have a working version with <kbd>Alt</kbd>+<kbd>Enter</kbd> now. I'll try upgrading `brick` to see if it's possible to use other modifiers. Thanks!
