### ISSUE TITLE
Automatically fill prelude module name when prelude name is typed

### ISSUE THREAD

**Issue by vrom911** [kowainik/summoner#255]
Like in CLI, assume that if the prelude name is `somePrelude` the prelude module name could be `SomePrelude`.

**Comment by Naman-sopho** [comment]
Hey, I would like to work on this feature.
From what I could gather the task at hand can be accomplished by adding to the validation logic [here](https://github.com/kowainik/summoner/blob/68286222cd66d00e6204006a8f20470183aca138/summoner-tui/src/Summoner/Tui/Validation.hs#L138). We can fill the `preludeModule` field with an appropriate value if the `preludeName` field is populated.

**Comment by ChShersh** [comment]
@Naman-sopho `isEmptyPrelude` shows validation error in the `Status` box when name of the prelude package is not empty, but the module name is empty. I think that this check should remain as it is, because it is still very useful if this issue is implemented.

The proper way to solve this issue would be to handle all key events when filling prelude package edit input and fill name of the module on-the-fly.

**Comment by Naman-sopho** [comment]
Sorry about the delay, the Brick documentation was a bit cryptic. I have completed an initial implementation which adds a[ `CustomPreludeName` pattern matching](https://github.com/Naman-sopho/summoner/blob/%23255-autofill-module-name/summoner-tui/src/Summoner/Tui.hs#L127) to an existing `VtyEvent` handler which dealt with checkbox activation. This triggers the [`autoFillPreludeModuleName`](https://github.com/Naman-sopho/summoner/blob/%23255-autofill-module-name/summoner-tui/src/Summoner/Tui.hs#L186) function which reloads a new form with the module name filled. But I am not sure how to implement the [`getUpdatedForm`](https://github.com/Naman-sopho/summoner/blob/%23255-autofill-module-name/summoner-tui/src/Summoner/Tui.hs#L193) i.e. how to extract the value from the Prelude field and insert it into the Module field thus creating the new form.

I have pushed the changes to my fork [here](https://github.com/Naman-sopho/summoner/tree/%23255-autofill-module-name).

**Comment by vrom911** [comment]
@Naman-sopho can you please make the PR if you think that we can help to proceed with the further work 🙂 It would be really nice to have these changes, however, the implementation might not be the easiest...

**Comment by juhp** [comment]
I feel it would be nice to use `NoImplicitPrelude` too: though it might depend on which prelude too.
