### ISSUE TITLE
Guess author name and email from VCS configs

### ISSUE THREAD

**Issue by m-renaud** [kowainik/summoner#261]
# Overview

`cabal init` guesses your name and email based on your source control configuration (`~/.gitconfig` for example), it would be awesome if Summoner did the same thing.

## Example

Currently the interactive prompt displays the following:

```
Repository owner:  [kowainik]
  ->   m-renaud
Short project description: 
  ->   
Author:  [Kowainik]
  ->   Matt Renaud
Maintainer e-mail:  [xrom.xkov@gmail.com]
  ->
```

The repository owner, author, and email can all be guessed from the users Git configuration file.

## Reference Code

The `cabal init` implementation can be found [here](https://github.com/haskell/cabal/blob/0c9792076b30257ff638bf6dd5a13b77ec7b22be/cabal-install/Distribution/Client/Init/Heuristics.hs#L247).

**Comment by vrom911** [comment]
@m-renaud Thanks for the idea! I guess, for Summoner at the moment it makes sense to only check the Git config file as we are supporting only this at the moment.

However, there is a way to configure this information for you in Summoner, even for different types of project creation (for example, your personal name, or organization one) – we are using TOML configurations. Here is some info about [what can be put to your `.toml` file](https://github.com/kowainik/summoner#file-configuration-), and also [the general logic we are using for the data input](https://github.com/kowainik/summoner#usage-).

**Comment by ChShersh** [comment]
@m-renaud See PR #305 which address the issue. From the `cabal init` code I see that it tries to guess credentials from multiple sources: environment variables, `darcs` config, `.gitconfig`, etc. Currently in `summoner` we support only `git` VSC, so it guess from `.gitconfig`.
