### ISSUE TITLE
Add option to turn-off cli colouring

### ISSUE THREAD

**Issue by vrom911** [kowainik/summoner#28]

**Comment by garg000dhruv** [comment]
@vrom911 I can help you with this but might need a bit more to go on.

**Comment by vrom911** [comment]
@garg000dhruv , thanks for this initiative!
To explain the situation, this is the screenshot of how it works now:
![screenshot from 2017-10-10 22-08-31](https://user-images.githubusercontent.com/8126674/31615283-c1185b98-b291-11e7-9fe3-3db9599031e4.png)
You can see different colors for printing different king of messages (we're using [`ansi-terminal`](https://hackage.haskell.org/package/ansi-terminal) library for that). I want to add cli argument like `--no-colors` (we're using [`optparse-applicative`](https://hackage.haskell.org/package/optparse-applicative) library) so all text won't be colorized. The reason for adding this option is that people can have customized terminal and these colors may not work okay for them. 

Hope it clarifies the issue a bit. If you have any questions about the code, libraries or anything else, I will happily answer them ;)

**Comment by garg000dhruv** [comment]
Thanks for the additional context. I'll take a look at this.

**Comment by vrom911** [comment]
We should also consider windows users. @puhlenbruck comment on that:
>The default background for the powershell console is blue, the prompt arrow colour is also blue here making it a bit hard to read, perhaps the colour scheme could be adjusted.

I think that this option can solve the problem for that also.

**Comment by ChShersh** [comment]
@vrom911 I propose to remove this issue from `1.0.0` milestone. Now it's much more difficult to add option to disable coloring...

**Comment by vrom911** [comment]
Agree, let's keep it for the next release

**Comment by ChShersh** [comment]
It was confirmed by @ShrykeWindgrace that colors are not a problem on Windows (at least when used with PowerShell) so I guess this issue can be closed.
