### ISSUE TITLE
Appveyor for Cabal?

### ISSUE THREAD

**Issue by vrom911** [kowainik/summoner#280]
I see that Cabal has this:
 https://github.com/haskell/cabal/blob/master/appveyor.yml

**Comment by ChShersh** [comment]
@vrom911 This is very nice! We can support both tools on CI completely :+1:

**Comment by ChShersh** [comment]
Since we now have `appveyor.yml` for `cabal` as well, we can support it 👍
* https://github.com/kowainik/summoner/blob/master/appveyor.yml
