### ISSUE TITLE
[RFC] `summon script` command

### ISSUE THREAD

**Issue by vrom911** [kowainik/summoner#285]
Usually, when I need to write a small standalone Haskell file, I need to google how to create a script file, or to look at previously written ones. The idea here is to have a command in Summoner which should create this file with some dummy function for you, which you can run immediately:

```shell
summon script 
```

Also, it should have `cabal` or `stack` option, so you can choose which one you'd like to create. Probably some other useful options for each of them.

I don't know yet about any hidden difficulties with this command, and I'm not sure if this could be useful for anyone else, so I'm happy to discuss the idea and details in this issue.

**Comment by ChShersh** [comment]
@vrom911 This is a nice suggestion! I would love to have this command :heart_eyes: For me it looks pretty straightforward. Just generate the file with:

1. Shebang
2. Comment with dependencies: only `base`
3. Content of the haskell module

Content can be very simple, like:

```haskell
main :: IO ()
main = putStrLn "Hello, world!"
```

That's all! Additional options I can think of:

1. Add `--ghc` option and specify bounds for `base` according to this option. By default the latest one will be used :slightly_smiling_face: 
2. `--name`: name of the file. **Open question:** Make it `Main.hs` by default?
3. `summoner` also can call `chmod +x <file_name>` command to make this file executable immediately. But something different needs to be done on Windows...

And, I guess, open question, is what to do with TUI? :thinking: It would be a shame to have this very useful command only in CLI mode... But probably some simple widget can be created for TUI as well...

**Comment by srid** [comment]
Do you think it is a good idea to add Nix support to this feature?

We can expect the script to look [like this](https://gist.github.com/travisbhartwell/f972aab227306edfcfea#gistcomment-2852419):

```
#! /usr/bin/env nix-shell
#! nix-shell -p "haskellPackages.ghcWithPackages (pkgs: with pkgs; [lens])" -i runhaskell
main = print 1
```

Note that cabal is not even involved, as dependencies are fetched straight from nixpkgs.

**Comment by vrom911** [comment]
This is sure a reasonable addition, but only after the support of Nix in the main generation process. I will create an issue for that to keep an eye on this one!
