### ISSUE TITLE
Backspace is not handled correctly by the CLI on OSX Sierra

### ISSUE THREAD

**Issue by o1lo01ol1o** [kowainik/summoner#29]
So trying to delete a typo yields : `^?`

**Comment by vrom911** [comment]
I had the same issue on Ububntu. I even was asking Ubuntu community to help [in this SO question](https://askubuntu.com/questions/946492/backspace-doesnt-work-inside-running-bash-script).
This is probably bugs of [`process`](http://hackage.haskell.org/package/process). My issue was resolved when I globally moved to newer resolver (magic :crystal_ball:).
Probably this needs more investigation..
Thanks for pointing this out!

**Comment by banditpig** [comment]
Delete works fine on Sierra 10.12.6.

**Comment by ChShersh** [comment]
@o1lo01ol1o Do you still have issue with Backspace?

**Comment by o1lo01ol1o** [comment]
nope
