### ISSUE TITLE
Support gitlab?

### ISSUE THREAD

**Issue by locallycompact** [kowainik/summoner#296]
Hi, any chance of expanding to support preconfiged use with gitlab? I currently manually maintain a collection of template repositories for gitlab ([example here](https://gitlab.com/zenhaskell/rio-etc-template/)). Wondering if this would be considered in the scope of this project.

**Comment by vrom911** [comment]
@locallycompact, thanks for your suggestion!

Summoner was initially designed as the tool with the support of GitHub integration, and therefore I see some issues with the maintenance of another Platform.

<hr>

Here are a few points that come to my mind straight away:

* Summoner uses `hub` tool to create repositories. But `hub` doesn't support GitLab. You can see [this issue for the reference](https://github.com/github/hub/issues/1383). This would mean that we need to depend on another third-party tool (not even official one) and request users to install it to guarantee the full functionality of our tool.
* We need to come up with another CI settings as I understand GitLab has its own GitLab CI and I'm not sure that our Travis or Appveyor integration would still be valid.
* Interactive terminal process of project creation would become even more scary and long.
* It's not clear how to change TUI accordingly. TUI interface should be intensely redesigned to provide an adequate interface for the new settings and not to complicate it for current users.
* As I am not a user of GitLab, it remains the huge question how to implement, test and maintain this big feature properly. As a good example, the Nix support for Summoner is still not finished as none of the maintainers of Summoner use it on a daily basis. Though @chessai put a lot of effort to it (which I'm very grateful to him for :clap:), he couldn't afford to spend a lot of time to maintain it which means we can not finish the feature and release it until we have anybody who would volunteer to help with it. We are a small non-profitable open source organisation, and we don't have any funds to hire people, unfortunately, so our hands a bit tight..

<hr>

After thinking on this a bit I wonder if it makes more sense to create another package (something like `summoner-gitlab`) which could depend on the main `summoner` package and implement required logic for GitLab support. The package shouldn't necessarily be inside this repo, btw. If you think that this is an appropriate solution would you have the will to work on it?

**Comment by kahlil29** [comment]
The idea for `summoner-gitlab` sounds good  👍

**Comment by vrom911** [comment]
@locallycompact I assume we agreed on the decision not to include this to Summoner. 

@locallycompact , @kahlil29  Feel free to create `summoner-gitlab` and ask if you have any further question.

I think we can close this issue.
