### ISSUE TITLE
option or way to delay creation of github project

### ISSUE THREAD

**Issue by juhp** [kowainik/summoner#300]
Sometimes I don't want to create a new github project immediately...
Pushing a skeleton project immediately to github etc is not always useful.
Maybe an optiion just to setup a local git repo would be useful.

I would prefer to do initial github push as a separate step.

**Comment by vrom911** [comment]
Thanks for your suggestions, @juhp!
We actually do have the option to do this. If you use CLI you can add `--no-upload` option, it would create all the files locally (even GitHub related ones), but without uploading to GitHub, just like you requested in this issue. If you use TUI there is also "No upload" checkbox in the GitHub section.

Let me know if this covers what you were looking for :slightly_smiling_face:

**Comment by juhp** [comment]
Thanks I will try that, great :+1:
