### ISSUE TITLE
Add 'no-upload' into toml Config

### ISSUE THREAD

**Issue by vrom911** [kowainik/summoner#303]
After #300 I starting to think that this could be handy.

**Comment by vrom911** [comment]
@juhp, this could be interesting for you.
I just made the PR (#306) that introduces `noUpload` option to config files.
Now you can add

```toml
noUpload = true
```

to the `.summoner.toml` file and it won't ever upload the project to GitHub.

This is just an additional feature. You can always use `--no-upload` flag as well.

**Comment by juhp** [comment]
Thanks
