### ISSUE TITLE
add summoner-tui to Hackage?

### ISSUE THREAD

**Issue by juhp** [kowainik/summoner#310]
Can summoner-tui be added to Hackage?
Is there some reason it is not there?

**Comment by vrom911** [comment]
@juhp , should be no problem!

The reason is probably already outdated – the TUI was an experimental feature.

**Comment by vrom911** [comment]
Done: https://hackage.haskell.org/package/summoner-tui-0.1.0

**Comment by juhp** [comment]
Ah okay, I see thanks - I thought it was rather nice :-)

**Comment by juhp** [comment]
But if you no longer support it, maybe it is better to remove it from the README later.

**Comment by vrom911** [comment]
Oh, no we *do* support TUI. We actually actively working on it. The new version of `summoner-tui` was released along with the new version of the main package and it covers all the features in the `summoner` along with a number of TUI only improvements. You can see the CHANGELOG:

https://github.com/kowainik/summoner/blob/master/summoner-tui/CHANGELOG.md#010--apr-9-2019

The "experimental" word in that sentense means mostly that the main package is not affected by TUI and that TUI doesn't not work on Windows which means that it's not the replacement for CLI. Just the addition which some people could like (while some don't).

**Comment by juhp** [comment]
Ah that's great to hear - (I think cabal-install confused me into thinking that it was still based on 1.2.0).
