### ISSUE TITLE
RFE: record version of summoner used to create project

### ISSUE THREAD

**Issue by juhp** [kowainik/summoner#313]
Sorry if I bombarding with requests etc.
It would be nice if summoner recorded its version when creating a project.
eg It could be noted in Changelog.md or the initial git commit.

**Comment by ChShersh** [comment]
I think this can be useful. We discussed similar feature with @vrom911 just yesterday! Possible way to put this information:

1. `.cabal` file (looks like the most reasonable place)
2. CHANGELOG.md
3. Initial git commit (not everybody want git integration, so we will lose this info in some cases)
4. README.md (this looks like a more general place for docs, not for meta-information)

The format of the message is to be discussed as well. But probably we can just put the output of the `summon --version` command.

**Comment by chshersh** [comment]
After more consideration, we decided that recording the `summoner` version, which was used for scaffolding the project, doesn't provide many benefits, only introduces more metadata into project creation. This can sometimes be noisy and unnecessary. So I'm closing this issue to have a cleaner and smaller generated project.
