### ISSUE TITLE
Add CODEOWNERS to github repository generated by 'summoner'

### ISSUE THREAD

**Issue by ChShersh** [kowainik/summoner#32]
Recent GHC introduced CODEOWNERS feature. It would be great to generate some default file for github repositories.

Example: https://github.com/serokell/importify/blob/master/CODEOWNERS

Announce: https://github.com/blog/2392-introducing-code-owners

**Comment by luvhalvorson** [comment]
Wasn't sure what you want here. I made a PR anyway, for Hacktoberfest is about to end. might look kinda silly tho. Would like to improve it if you can provide details :)

**Comment by vrom911** [comment]
@ChShersh  thanks for this wonderful idea! It's definitely worth it to have it!
@luvhalvorson  I made some comments in your PR, thank you :)

**Comment by ChShersh** [comment]
Turned out it's not useful to have CODEOWNERS until we figure out how to support user vs. organization.

**Comment by vrom911** [comment]
A subtask of #41. Better to keep all of such kind in one place.
(Also it's not clear how to handle this one)
