### ISSUE TITLE
Use key-value map for extra files

### ISSUE THREAD

**Issue by chshersh** [kowainik/summoner#333]
Currently, we've hardcoded some of the files in the `.toml` config, for example:

```haskell
stylish.url = "https://raw.githubusercontent.com/kowainik/org/master/.stylish-haskell.yaml"
contributing.url = "https://raw.githubusercontent.com/kowainik/org/master/CONTRIBUTING.md"
```

This approach is not extensible because:

1. It doesn't allow `summoner` users to bring their own files.
2. It requires to change Haskell code each time we want to add new files.

Since `tomland-1.1` we now have the support for inline tables. And after [this issue](https://github.com/kowainik/tomland/issues/203) is implemented we can have only single field in the config of the type `Map FilePath Source` and in the configuration it will look like this:

```haskell
extra.files =
    [ { file = ".stylish-haskell.yaml", url = "https://raw.githubusercontent.com/kowainik/org/master/.stylish-haskell.yaml" }
    , { file = "CONTRIBUTING.md", url = "https://raw.githubusercontent.com/kowainik/org/master/CONTRIBUTING.md" }
    ]
``` 

What do you think?

The implementation includes:

- [x] Add `Map FilePath Source` field to config
- [x] Create files from the `Map`
- [x] Write deprecation messages
- [x] Pretty tree display in TUI

**Comment by vrom911** [comment]
Wow, this is a wonderful idea! I'm fully for this :+1:

**Comment by chshersh** [comment]
This also allows to support `nix` in a simpler way: other people can bring their own additional files if they want and `summoner` can support only bare minimum.

**Comment by chshersh** [comment]
@vrom911 I will try to do this :+1:
