### ISSUE TITLE
Avoiding symlinks in cabal source dists

### ISSUE THREAD

**Issue by srid** [kowainik/summoner#334]
I am working on adding a `default.nix` to summoner so that it can be built using Nix.

But there is a problem. The README/LICENSE of the two cabal packages symlink to their targets _outside_ of their directories (i.e., the parent directory). This causes issues with Nix build, because Nix copies the symlinks as is and `cabal build` would later fail.

I propose a couple of changes:

- Replace symlinks with regular files (toplevel/README.md can be a symlink, for Github rendering)
- Respect DRY by having, say, `summoner-tui/README.md` refer to the README of `summoner-cli/README.md`. This would reflect on the hackage docs correspondingly (currently there is README duplication between the -cli and -tui hackage docs because of the symlink).

What do you think? I can provide more context/ rationale for this change if needed. I cannot think of alternatives that will keep things as simple, but I'm open to suggestions.

**Comment by srid** [comment]
To see how it all would look like, see https://github.com/srid/summoner/tree/nixify

**Comment by vrom911** [comment]
Hey @srid, thanks for working on Nix integration!

Have you tried to address this Nix issue to Nix itself? I do see problems with both of the proposed solutions, which is not making life easier. I would prefer to keep things as it is and to fix the problem with nix itself if it's possible. Please share your updates on the topic, thanks! :slightly_smiling_face:

**Comment by srid** [comment]
It is not really an issue with Nix per se, as having symlinks pointing to files outside the source directory is considered impure.

I could customize the `default.nix` to manually copy over the target files into the source derivation; I'll give that a try.

**Comment by srid** [comment]
Worked around in https://github.com/kowainik/summoner/pull/335/commits/b57710a3573dc9b3021797aaa2e48ef08e49a88f
