### ISSUE TITLE
Build summoner with GHC-8.8

### ISSUE THREAD

**Issue by vrom911** [kowainik/summoner#338]
TODO:
- [x] Update Travis config
- [x] Add `-Wmissing-deriving-strategies` to `.cabal` file ghc options

**Comment by gableh** [comment]
Interested in working on this, whats the difference between this and #339 though?

**Comment by vrom911** [comment]
Thanks for your enthusiasm, @gableh :blush: 

This issue is about building the `Summoner` project with GHC-8.8.1, which includes support on the CI. Number 339, in turn, is about making version 8.8 default in the generated by Summoner projects, which would require much more to do. One of the blocking issues for 339 is the fact that Stackage doesn't have a stable release for 8.8 yet, so we should wait for that at least :slightly_smiling_face:

**Comment by gableh** [comment]
Ah okay, will tomland 1.2.0.0 be released any time soon? I think it needs to be updated before this since the current version depends on base < 4.13

**Comment by chshersh** [comment]
@gableh I believe `tomland` is not the only library that blocks `summoner`. There is also `relude`. And for `relude` we have `0.6.0.0` milestone which includes some issues that need to be done first. But Hacktoberfest helps a lot in closing those issues, so probably these two libraries will see their release soon :+1:
