### ISSUE TITLE
Support GHC-8.8

### ISSUE THREAD

**Issue by vrom911** [kowainik/summoner#339]
- [ ] Change default GHC
- [ ] Add and change default stack LTS

**Comment by patrickt** [comment]
Would love this, as my personal and work projects are all 8.8/base 4.13 now.

**Comment by vrom911** [comment]
Thanks for pinging, @patrickt !

Yes, I agree that the default one should be 8.8 at the moment. I am personally using 8.8 for my projects as well (where possible :smiley:). The stopper for us is that there is no stable LTS for 8.8 yet, somehow it takes much more time than we expected. What we can do is to support 8.8 in the master with the latest nightly resolver for Stack; however, I wouldn't release it without the stable snapshot though :disappointed: 

Would that option work for you? I am sorry for the inconvenience.

**Comment by patrickt** [comment]
@vrom911 That works fine! Happy to install from master.
