### ISSUE TITLE
Github password.

### ISSUE THREAD

**Issue by banditpig** [kowainik/summoner#34]
If incorrect password or typo  for Github is given there's no opportunity to try again. 
e.g. Just supplied  github username and then asked for password.
----------------
github.com password for banditpig (never stored): ...enter wrong password or a typo
Error creating repository: Unauthorized (HTTP 401)
Bad credentials
hs-init: callCommand: hub create -d 'Tuple space' banditpig/tspace (exit 1): failed
------------------

**Comment by vrom911** [comment]
@banditpig  thanks for noticing this! This one is cool to have done.
I'm using ssh, so I'll some time need to investigate how to proceed with password reentering with `hub`.

**Comment by banditpig** [comment]
Looking at the man page for hub is says  "...To avoid being prompted, use GITHUB_USER and GITHUB_PASSWORD environment variables.". Which might help a little?

**Comment by ChShersh** [comment]
@banditpig I would say that using `ssh` key is recommended way to work with both `git` and GitHub. I guess `hs-init` can check for environment variables `GITHUB_USER` and `GITHUB_PASSWORD` and print some warning but only in case when `ssh` key is not present. Though, I'm not sure how to check whether there's `ssh` key or not...
