### ISSUE TITLE
Move to cabal-3.0

### ISSUE THREAD

**Issue by chshersh** [kowainik/summoner#340]
This change implies:

- [x] Changing `defaultCabal`
- [x] Removing `v2-` prefixes
- [x] Simplify `cabal test` (`echo "No tests"` no longer needed)
- [x] Add `--write-ghc-environment-files=always` option

The following files need to be changed:

- [ ] `.travis.yml`
- [ ] Generated `.travis.yml`
- [ ] `appveyor.yml`
- [ ] Generated `appveyor.yml`
- [ ] `.github/workflows/ci.yml`
- [ ] Generated `.github/workflows/ci.yml`

**Comment by vrom911** [comment]
And changing cabal version in `.cabal` file and `.travis.yml`.

**Comment by srid** [comment]
> Future: generated default.nix

Could you elaborate on what this means? I thought `default.nix` is hand-written?

**Comment by chshersh** [comment]
@srid The word _generated_ in the context of this project means _files and directories generated by `summoner` during his work_. So ideally we are trying to use the same CI configs as `summoner` would generate during scaffolding. Dogfooding this project helps to improve UX :+1: 

After looking closely at `default.nix` again I don't see any `cabal`-related information in this package.... So we might not even need to change it at all if it uses `cabal >= 3.0` by default.

**Comment by szabi** [comment]
Is Grzegorz  @gdziadkiewicz still working on this?

**Comment by gdziadkiewicz** [comment]
@szabi I'm not
