### ISSUE TITLE
Create '.stylish-haskell.yaml' in project

### ISSUE THREAD

**Issue by ChShersh** [kowainik/summoner#35]
`stylish-haskell` works that way that it applies rules from `.stylish-haskell.yaml` inside project root if it's there. So it's rather convenient to put some `stylish-haskell` config inside created project if you want to follow some style and want your contributors to use your `stylish-haskell` config.

At first I propose to put [Serokell's `.stylish-haskell.yaml`](https://github.com/serokell/serokell-util/blob/master/.stylish-haskell.yaml) which is quite reasonable and convenient.

**Comment by vrom911** [comment]
@ChShersh Very nice idea! Thank you!
I think that it should be optional. Or maybe by default it should add global `.stylish-haskell.yaml` as many people could have their own files for their needs, but it also should be possible to apply `Serokell` file as a very good example, or to specify any other file. Should think about the best design a little more :thinking:

**Comment by ChShersh** [comment]
@vrom911 I agree, this configuration is more specific than others. And several options are possible. I propose next interface:

1. `off` by default (but ask about it during interactive process).
2. Some option to use default _Serokell_ `.stylish-haskell.yaml`, like `--stylish serokell`
3. Some option to use global config from `~/.stylish-haskell.yaml`, like `--stylish global`
4. Reject other strings passed to `--stylish`.

But it's not obvious to me at all how to integrate these options into current `on` `off` interface. Because in `on` you want to enable specific configuration. And in `off` you want to disable every.

I think best we can do for now is to have only one option — `--stylish` — which just copies `~/.stylish-haskell.yaml` and produces warning if you specified option but file wasn't found.
