### ISSUE TITLE
Support GitHub actions

### ISSUE THREAD

**Issue by chshersh** [kowainik/summoner#351]
They seem to work pretty nice and they have native support for Haskell with the following template:

* https://github.com/actions/setup-haskell

So we can support them in `summoner` as well, specifically:

- [ ] Create `.github/workflows/ci.yml` file
- [ ] Create a badge in README

The only questions is how to configure them properly, maybe we want to support `cachix`

**Comment by vrom911** [comment]
That's actually awesome idea!

Probably, to use it we want users to specify their cachix name then if we decide to go with that option. But I see that there are several ways to build in there. It all should depend on the build tool selected for the project, I guess.

**Comment by chshersh** [comment]
The only restriction I can think of now is not to allow to use `cachix` if the user didn't select Nix build tool. And probably not allow to create them if the user selected only Stack (because the default template is for Cabal)? And, btw, GitHub actions also support build matrix in a quite nice way, but there's no easy way to specify build matrix with Nix builds. So, unfortunately, some non-uniformity is going to be present in how we handle GitHub actions for various build tools...

**Comment by patrickt** [comment]
Please let me know if there’s anything that I can do to help out on this—I use GH Actions extensively for Haskell CI, and summoner support for it would be 💯

**Comment by chshersh** [comment]
@patrickt Thanks for your interest! Supporting GitHub actions shouldn't be that hard 🙂 But it requires to add changes in a few places:

* Add file template with content to the [`Summoner.Template.GitHub`](https://github.com/kowainik/summoner/blob/master/summoner-cli/src/Summoner/Template/GitHub.hs) module. It would be nice if template comes with GitHub CI cache already enabled as well (I think we won't go with `cachix` until we support Nix). I see that `setup-haskell` action supports Cabal and GHC matrix. I propose to use [`defaultCabal`](https://github.com/kowainik/summoner/blob/69fed8bb625728a1922a0b0180ead48b1b18e710/summoner-cli/src/Summoner/Default.hs#L29-L31) for the `cabal-install` version and populate the matrix as we do everywhere. Inside these actions all our usual `cabal new-*` commands should be used. It would be also nice to support HLint, but I see from [your issue](https://github.com/actions/setup-haskell/issues/5) that GitHub action for Haskell doesn't have HLint at the moment. It's not problem, we can add it later or just do it via `curl` as usual.
* Add a field to [the TOML config](https://github.com/kowainik/summoner/blob/69fed8bb625728a1922a0b0180ead48b1b18e710/summoner-cli/src/Summoner/Config.hs#L61-L63)
* Read this option [from CLI somewhere here](https://github.com/kowainik/summoner/blob/69fed8bb625728a1922a0b0180ead48b1b18e710/summoner-cli/src/Summoner/Project.hs#L88-L89). Since GitHub actions don't  support `stack`, I propose to ask for this CI only if `cabal` build tool is selected and only if GitHub is chosen.
* And as a last step it would be also nice to add this option to TUI interface (to form and settings) in [the corresponding group](https://github.com/kowainik/summoner/blob/69fed8bb625728a1922a0b0180ead48b1b18e710/summoner-tui/src/Summoner/Tui/Form.hs#L117-L125) but this will require to take some UX decisions since we have kinda dense TUI already... But we can help with TUI if you're willing to open a PR 🙂 

Does it make sense? Also, @vrom911, am I missing anything, does this look correct?

**Comment by vrom911** [comment]
Resolved in #393
