### ISSUE TITLE
Validate prelude package name

### ISSUE THREAD

**Issue by yigitozkavci** [kowainik/summoner#354]
As per [cabal spec](https://www.haskell.org/cabal/users-guide/developing-packages.html#package-names-and-versions) package names are subject to a well-defined format. We should add a validation for it in summoner-tui.

This is an issue created as an action item from #353.

Also, we could check the module name.

Parts need to be covered:

- [ ] CLI
- [x] Config
- [ ] TUI

**Comment by vrom911** [comment]
Sorry, I didn't notice earlier but this should be also checked in CLI. So let's make this issue to cover both  cases, so we don't forget them :slightly_smiling_face:
