### ISSUE TITLE
Merge CHANGELOGs for TUI and CLI

### ISSUE THREAD

**Issue by vrom911** [kowainik/summoner#362]
Sometimes I find it awkward to search for CHANGELOG information which is spread across both files.

I have a few arguments for having one file for CHANGELOG:

* All `summoner-cli` changes affect `summoner-tui` always, but this is not always reflected in the CHANGELOG.
* It's easier to understand the whole project direction through the single document.

What I propose to do is to 
+ standardise version for both CLI and TUI releases
+ have `[TUI]` `[CLI]` tags for each entry for the entire CHANGELOG file for the summoner project as a whole.

What are your thoughts? Will there be any drawbacks?

**Comment by chshersh** [comment]
@vrom911 That's an excellent idea! This will indeed make the process of maintaining both packages simpler. Regarding version policy: what do you think about having the same version for `summoner` and `summoner-tui`? Like, we will release `summoner-1.4.0.0` and `summoner-tui-1.4.0.0`. Considering the frequency of our release, I don't expect a lot of discrepancies in this version policy... Considering the fact that it should be okay to release minor version upgrades in case of bug fixes or minor changes.
