### ISSUE TITLE
Add some default-extensions

### ISSUE THREAD

**Issue by ChShersh** [kowainik/summoner#38]
Often people want to have some `default-extensions` inside their `.cabal` file. I'm not sure how interface should look like because not everyone likes `default-extensions` and not eveyryone agrees on which extensions should be enabled by default.

**Comment by vrom911** [comment]
@ChShersh , unfortunately, you're right, it never could be defined which are the best extensions to be added to the project, add giving this option as command line argument is not the greatest idea, as it will make `hs-init` difficult to work with. Probably anyway we will need to make some settings file, where users could configure this behavior also..

**Comment by ChShersh** [comment]
@vrom911 You might be right... I was thinking about some interactive process. But having config where user can specify desired extensions (and other options as well) may be a better solution for this problem. Also it's much more convenient to use. But introducing configuration file can increase difficulty of the project a lot, so I'm not sure that we should implement this unless we gather enough feedback...
