### ISSUE TITLE
summon assumes hub is installed

### ISSUE THREAD

**Issue by juhp** [kowainik/summoner#394]
Thanks for the new 1.4 release - looks nice!

It seems Github integration assumes `hub` is installed.

```
:
⚙  hub create -d 'Koji library' juhp/koji
/bin/sh: hub: command not found
summon: callCommand: hub create -d 'Koji library' juhp/koji (exit 127): failed
```

I am not too worried about this but thought I would just report it for awareness.

A few options:
(a) don't do anything about it - the error is easy to understand and can be fixed manually  afterwards anyway.
(b) don't offer Github integration if hub not installed: or output a warning instead
(c) don't use hub - but hub is probably the simplest way for now.

**Comment by vrom911** [comment]
Thank you very much, @juhp !

Yes, we are aware of the requirement. As it's the easiest working option to create a project on GitHub we decided to go with `hub` from the beginning. It's also not so rarely used tool, as far as I know. 

We did put it in the [section with prerequisites](https://github.com/kowainik/summoner#prerequisites-) in the Summoner's README file.

I don't want to give up on `hub` as it solves a lot of issues with the GitHub project creation. (b) is a reasonable option, however it also can overcomplicate the check very quickly. Need to think more on the benefits from such check, which are not as great at first glance :thinking:

**Comment by vrom911** [comment]
I decided to go with the following option:

If the process comes to the GitHub repository creation step, then we should check if the `hub` exe exists on the user machine. If it does not then we will print some descriptive message, but won't fail.
