### ISSUE TITLE
Support full 'Community' list

### ISSUE THREAD

**Issue by chshersh** [kowainik/summoner#41]
I just discovered where you can see all files which are considered by GitHub:

* https://github.com/vrom911/hs-init/community

I think, it's a good idea to make `hs-init` create these files.

What `hs-init` can do:
- [x] Description 
- [x] README
- [ ] Code of conduct
- [x] Contributing (#31)
- [x] License
- [ ] Issue or pull request template 
- [ ] Codeowners (#32)

**Comment by AlexBoliachiy** [comment]
Gonna take this one

**Comment by ChShersh** [comment]
@AlexBoliachiy To be clear, this issue is about patching `summoner` to generate projects with Code of Conduct. I think this can be done in the same way it's done for `.stylish-haskell.yaml` and CONTRIBUTING.md

**Comment by chshersh** [comment]
This is a special case of #333, so I'm closing this issue as redundant.
