### ISSUE TITLE
Support GHC-8.10 in generated projects

### ISSUE THREAD

**Issue by vrom911** [kowainik/summoner#444]
And make it default.

This require testing all CI setting against GHC-8.10 as well.

**Comment by marcin-rzeznicki** [comment]
Would be lovely to see this. Arch just migrated to GHC-8.10.1

**Comment by vrom911** [comment]
Glad to hear :blush: 
Currently, this is blocked by Stack resolvers, unfortunately..

**Comment by marcin-rzeznicki** [comment]
Ah, drat, right :unamused: Looking forward to it then and keep up the great work - summoner is a really indispensable tool. Thanks
