### ISSUE TITLE
summon-tui with no arguments fails with `hPutChar: invalid argument`

### ISSUE THREAD

**Issue by nuttycom** [kowainik/summoner#472]
```
nuttycom@dominion:~/workλ summon-tui

                                                   ___
                                                 summon-tui: <stderr>: hPutChar: invalid argument (invalid character)
```

**Comment by vrom911** [comment]
Can you please provide more details? Is it a Windows issue? Have you tried to set up your locale?

**Comment by vrom911** [comment]
Summoner TUI is not supposed to work on Windows due to [this issue in the vty library](https://github.com/jtdaugherty/vty/pull/1).
And it is specified in the documentation.
As no more details provided I assume this question resolved as everything tested to be working on other platforms.
