### ISSUE TITLE
Remove `neat-interpolation`

### ISSUE THREAD

**Issue by vrom911** [kowainik/summoner#477]
It prevents us from being on Stackage.

As the messy workaround of the breaking design of the `neat-interpolation`, we could use manual indentation and `Text` appending.

**Comment by TristanCacqueray** [comment]
Why does `neat-interpolation` prevent from being on Stackage, isn't that enough: https://www.stackage.org/package/neat-interpolation ?

Any by manual indentation, do you mean that:

```haskell
    createExe =
        [text|
        module Main (main) where

        import $libModuleName (someFunc)

        main :: IO ()
        main = someFunc
        |]
```

would be replaced by:

```haskell
    createExe = unlines [
      "module Main (main) where"
    , ""
    , "import " <> libModuleName <> " (someFunc)"
    , ""
    , "main :: IO ()"
    , "main = someFunc"
    ]
```
?

**Comment by vrom911** [comment]
Because the new version of neat-interpolation has changes in the design that break the alignment in Summoner.

We already working on the issue, @TristanCacqueray .
