### ISSUE TITLE
Make GH Actions template point to haskell-ci/setup

### ISSUE THREAD

**Issue by patrickt** [kowainik/summoner#522]
The original [`actions/setup-haskell`](https://github.com/actions/setup-haskell/pull/56) GitHub Action repository is being deprecated in favor of one by the community at https://github.com/haskell-ci/setup. The `ci.yml` template should be changed to point to the new repo.

**Comment by lierdakil** [comment]
Heads-up: the up-to-date fork is in the main Haskell org at https://github.com/haskell/actions for reasons. Also, actions/setup-haskell has been completely broken for the last month or two. So this issue is somewhat pressing.

**Comment by patrickt** [comment]
This appears to be have been fixed: https://github.com/kowainik/summoner/blob/main/.github/workflows/ci.yml#L26-L30

**Comment by lierdakil** [comment]
Actually, no. Summoner still generates CI config referencing the old actions/setup-haskell action, e.g.
https://github.com/kowainik/summoner/blob/ad94d72e9dfe3f154d462c10d80896a1c332276c/summoner-cli/src/Summoner/Template/GitHub.hs#L152-L157
https://github.com/kowainik/summoner/blob/ad94d72e9dfe3f154d462c10d80896a1c332276c/summoner-cli/examples/full-batteries/.github/workflows/ci.yml#L50-L55
ad94d72e9dfe3f154d462c10d80896a1c332276c being the current HEAD.

**Comment by patrickt** [comment]
Ah, my bad, that was the project's `ci.yml` rather than the embedded file itself. My mistake
