### ISSUE TITLE
Provide statically-linked Linux builds

### ISSUE THREAD

**Issue by lierdakil** [kowainik/summoner#534]
I've just run into this: got the binaries to play around and, nope, different library layout, can't run those. Perhaps providing statically-linked binaries would be a better option?

I've had some success producing static binaries with GitHub actions on Alpine with pandoc-crossref (see [here](https://github.com/lierdakil/pandoc-crossref/blob/master/.github/workflows/haskell.yml)). And summoner seems to produce a reasonable static build (did a quick test; 17M summon, 20M summon-tui; both around 3M xz-ipped)

Let me know if you need some help setting that up.

**Comment by chshersh** [comment]
We have experience providing static binaries for executables, and the new Summoner releases will have CI to generate those releases. The [latest major Summoner](https://github.com/kowainik/summoner/releases/tag/v2.0.0.0) release has a static executable.

It would be nice if the Haskell GitHub Action provided an easy way to generate statically-linked binaries, but there's no such way at the moment, though it's clear, how to do this with a bit of work.

* https://github.com/haskell/actions/issues/9

**Comment by vrom911** [comment]
Closed in favour of #537

**Comment by lierdakil** [comment]
@vrom911 GitHub Actions doesn't automagically make builds static, some setup is required, so I don't see how #537 subsumes this issue.
