### ISSUE TITLE
Add option to use `base-noprelude` approach when using alternative Prelude

### ISSUE THREAD

**Issue by suhdonghwi** [kowainik/summoner#550]
I use [haskell-language-server](https://github.com/haskell/haskell-language-server) when programming in Haskell. hls makes use of `stack repl` underneath, [which does not work on project using `mixins`](https://github.com/commercialhaskell/stack/issues/5077). `summoner` uses `mixins` approach by default so it does not work with `haskell-language-server` well. I need to change project settings to use `base-noprelude` approach everytime manually. It would be great if I can configure this behavior.

Thank you!

**Comment by chshersh** [comment]
`base-noprelude` doesn't support recent GHC versions and generally is not maintained. So it's not possible to have this feature working for all GHC versions supported by Summoner.
