### ISSUE TITLE
Add 'show ghc' and 'show license' commands

### ISSUE THREAD

**Issue by ChShersh** [kowainik/summoner#63]

**Comment by ChShersh** [comment]
Note, that this is an extremely breaking change. It requires to change CLI interface. So we're going to introduce `new` command. And you can create packages with:

```
summon new name-of-the-package
```

Unfortunately, this is a required change to move further.

**Comment by willbasky** [comment]
`summon show ghc` will show list of all available **ghc versions**? 
`summon show license MIT` to show **MIT** license text?
`summon show license BSD2` to show **BSD2** license text?

**Comment by ChShersh** [comment]
@willbasky Yes, that's right. With one addition:

* `summon show license`: shows names of all supported licenses. So if now license name is given then it should print name of all available licenses with a hint like `Use show license [LICENSE_NAME]` command to see body of license.

**Comment by willbasky** [comment]
> So we're going to introduce new command. And you can create packages with: `summon new name-of-the-package`

To make just interface blank without implementation in logic?

**Comment by ChShersh** [comment]
> To make just interface blank without implementation in logic?

Sorry, if I wasn't clear. Currently, you can create package with the following command:

```
summon name-of-the-package
```

But after we add `show` command, we have conflict. Consider this usage example:

```
summon show
```

What this command should do? It's ambiguous because it has two possibilities:

1. Create package with name `show`.
2. Show `--help` message for `summon show` command.

Ambiguity in CLI is very bad. So there's only one option: change existing interface of `summoner`. So `summon name-of-the-package` will be no longer a valid command. To create package you need to write:

```
summon new name-of-the-package
```
