### ISSUE TITLE
Add 'summon config' command

### ISSUE THREAD

**Issue by chshersh** [kowainik/summoner#70]
This command should create `.summoner.toml` file in interactive, user-friendly way. Also, probably it can have better name than `summon init`.

**Comment by vrom911** [comment]
@ChShersh, Probably `summon setup`?
Also, is this blocked by some issue with the cli changes? Or this can be done independently? (But still `summon new` should be introduced here)

**Comment by ChShersh** [comment]
@vrom911 I don't like both `summon init` and `summon setup`. Names `init` and `setup` implies that `summoner` needs to be configured before using. While in reality it doesn't require any configuration in advance. It works without `.summoner.toml`. So it's better to have something like `summon create-config` (but with better name).

Proposed alternatives: `create-config`, `make-config`, `configure`, `remember-choices`, `cache-options`.

Anything better? @willbasky @ghallak your suggestions are appreciated as well!

**Comment by vrom911** [comment]
Yeah, I agree with you.
My favourite one from the suggestions is `configure`.

**Comment by willbasky** [comment]
I suppose `summon toml` explicitly says  about what will be created.
