### ISSUE TITLE
Add stackage badges to README

### ISSUE THREAD

**Issue by ChShersh** [kowainik/summoner#82]
Just like here:

* https://github.com/kowainik/relude

**Comment by vrom911** [comment]
Do we need to add this if it's only `cabal` project? Probably it should be only appended if `stack == True`?

**Comment by ChShersh** [comment]
@vrom911 Yes, you're absolutely right. This should be added only if `stack == True`.

**Comment by willbasky** [comment]
![screenshot_20180730_133520](https://user-images.githubusercontent.com/28530747/43386656-c5b102b0-93fd-11e8-844a-ae1ce3d3409f.png)

Stackage badges used now is not fitted and must be refactor as you show next. Right?

**Comment by ChShersh** [comment]
@willbasky `summoner` creates new Haskell projects with `README.md` files. Generated `README.md` file doesn't contain Stackage badges now. So this issue is about adding those badges to user packages automatically.
