### ISSUE TITLE
Travis fails for GHC < 8.2

### ISSUE THREAD

**Issue by adituv** [kowainik/summoner#92]
As title, because `-fhide-source-paths` was only added in GHC 8.2.  Maybe only add it conditionally to the template?

**Comment by ChShersh** [comment]
@adituv Thanks for bug report! Yeah, this should be done conditionally in this function:

https://github.com/kowainik/summoner/blob/bb0b4915adff0f7a7261de2646d265dacb98d837/src/Summoner/Template.hs#L425

Would you like to open pull request with this bug-fix?
