### ISSUE TITLE
Travis for `cabal`

### ISSUE THREAD

**Issue by vrom911** [kowainik/summoner#97]
This is subtask of #96 , but I would like to have a place for discussion of Travis settings.

The way to do `.travis.yaml` for cabal project that I know is [`haskell-ci`](https://github.com/haskell-CI/haskell-ci) (I used this solution for `o-clock` when it started, but then it was replaced with much simpler one). So I'm not sure which way to go here as I don't know how the support of several `ghc`s with `cabal` at the same time will affect our settings (if not to choose `haskell-ci`). And also what to do for both `cabal` and `stack` option.

**Comment by ChShersh** [comment]
@vrom911 It would be nice to use `haskell-ci` but as I can see from `o-clock`'s commit history, `.travis.yml` file generated by `haskell-ci` is pretty complicated. And doesn't use `new-build` feature. So I prefer to come up with our own travis config.

We could start with adding `cabal` Travis support for multiple GHCs to `summoner` (or some other project). And see how it goes.

**Comment by int-index** [comment]
I agree that the machinery `haskell-ci` generates is overcomplicated. I think `o-clock` has fairly good `cabal new-build` Travis support and we should generate something similar.
